app/models.py
from datetime import datetime
from app import db

class Creator(db.Model):
    __tablename__ = 'creators'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), unique=True)
    image = db.Column(db.String(255))
    
    models = db.relationship('Model', backref='creator', lazy='dynamic')
    
    def __repr__(self):
        return f'<Creator {self.username}>'

class Model(db.Model):
    __tablename__ = 'models'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    description = db.Column(db.Text)
    allow_no_credit = db.Column(db.Boolean, default=False, name='allowNoCredit')
    allow_derivatives = db.Column(db.Boolean, default=False, name='allowDerivatives')
    allow_different_license = db.Column(db.Boolean, default=False, name='allowDifferentLicense')
    type = db.Column(db.String(50))
    minor = db.Column(db.Boolean, default=False)
    sfw_only = db.Column(db.Boolean, default=True, name='sfwOnly')
    poi = db.Column(db.Boolean, default=False)
    nsfw = db.Column(db.Boolean, default=False)
    nsfw_level = db.Column(db.Integer, default=0, name='nsfwLevel')
    availability = db.Column(db.String(50))
    cosmetic = db.Column(db.String(255))
    supports_generation = db.Column(db.Boolean, default=False, name='supportsGeneration')
    creator_id = db.Column(db.Integer, db.ForeignKey('creators.id'))
    download_count = db.Column(db.Integer, default=0, name='downloadCount')
    
    versions = db.relationship('ModelVersion', backref='model', lazy='dynamic')
    tags = db.relationship('Tag', backref='model', lazy='dynamic')
    
    def __repr__(self):
        return f'<Model {self.name}>'

class ModelVersion(db.Model):
    __tablename__ = 'modelVersions'
    
    id = db.Column(db.Integer, primary_key=True)
    model_id = db.Column(db.Integer, db.ForeignKey('models.id'))
    index_in_model = db.Column(db.Integer, name='index_in_model')
    name = db.Column(db.String(255))
    base_model = db.Column(db.String(100), name='baseModel')
    base_model_type = db.Column(db.String(100), name='baseModelType')
    published_at = db.Column(db.String(), name='publishedAt')
    availability = db.Column(db.String(50))
    nsfw_level = db.Column(db.Integer, default=0, name='nsfwLevel')
    description = db.Column(db.Text)
    supports_generation = db.Column(db.Boolean, default=False, name='supportsGeneration')
    download_url = db.Column(db.String(255), name='downloadUrl')
    download_count = db.Column(db.Integer, default=0, name='downloadCount')
    
    files = db.relationship('File', backref='model_version', lazy='dynamic')
    images = db.relationship('Image', backref='model_version', lazy='dynamic')
    
    def __repr__(self):
        return f'<ModelVersion {self.name}>'

class File(db.Model):
    __tablename__ = 'files'
    
    id = db.Column(db.Integer, primary_key=True)
    size_kb = db.Column(db.Float, name='sizeKB')
    name = db.Column(db.String(255))
    type = db.Column(db.String(50))
    pickle_scan_result = db.Column(db.String(50), name='pickleScanResult')
    pickle_scan_message = db.Column(db.Text, name='pickleScanMessage')
    virus_scan_result = db.Column(db.String(50), name='virusScanResult')
    virus_scan_message = db.Column(db.Text, name='virusScanMessage')
    scanned_at = db.Column(db.String(), name='scannedAt')
    format = db.Column(db.String(50))
    model_version_id = db.Column(db.Integer, db.ForeignKey('modelVersions.id'), name='modelVersion_id')
    sha256 = db.Column(db.String(64))
    autov1 = db.Column(db.String(255))
    autov2 = db.Column(db.String(255))
    autov3 = db.Column(db.String(255))
    crc32 = db.Column(db.String(8))
    blake3 = db.Column(db.String(64))
    download_url = db.Column(db.String(255), name='downloadUrl')
    primary_file = db.Column(db.Boolean, default=False, name='primaryFile')
    
    def __repr__(self):
        return f'<File {self.name}>'

class Image(db.Model):
    __tablename__ = 'images'
    
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(255))
    nsfw_level = db.Column(db.Integer, default=0, name='nsfwLevel')
    width = db.Column(db.Integer)
    height = db.Column(db.Integer)
    hash = db.Column(db.String(64))
    model_version_id = db.Column(db.Integer, db.ForeignKey('modelVersions.id'), name='modelVersion_id')
    
    def __repr__(self):
        return f'<Image {self.id}>'

class Tag(db.Model):
    __tablename__ = 'tags'
    
    id = db.Column(db.Integer, primary_key=True)
    model_id = db.Column(db.Integer, db.ForeignKey('models.id'))
    tag = db.Column(db.String(100))
    
    def __repr__(self):
        return f'<Tag {self.tag}>'

app/routes.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    current_app,
)
from app.models import Creator, Model, ModelVersion, File, Image, Tag
from app import db
from flask_paginate import Pagination, get_page_parameter
import os

main = Blueprint("main", __name__)


@main.route("/")
def index():
    # Get NSFW filter parameter
    nsfw = request.args.get("nsfw", "false")

    # Base query with NSFW filtering
    random_models_query = Model.query

    # Apply NSFW filter if needed
    if nsfw == "false":
        random_models_query = random_models_query.filter(Model.nsfw == False)

    # Get random models with their base models
    # We need to join with ModelVersion to get the base model info
    random_models = random_models_query.order_by(db.func.random()).limit(10).all()

    # Pre-fetch model versions for each model to avoid N+1 query problems
    for model in random_models:
        # Make sure each model has at least the first version loaded
        if model.versions.count() > 0:
            model.first_version = model.versions.first()
        else:
            model.first_version = None

    # Get random images for the banner (filtered for NSFW)
    # We need to be more explicit with our joining and filtering to ensure NSFW models don't show up
    if nsfw == "false":
        # This query ensures that we properly join and filter NSFW content
        featured_images = (
            db.session.query(Image)
            .join(ModelVersion, Image.model_version_id == ModelVersion.id)
            .join(Model, ModelVersion.model_id == Model.id)
            .filter(Model.nsfw == False)
            .order_by(db.func.random())
            .limit(5)
            .all()
        )
    else:
        # If NSFW is allowed, just get random images
        featured_images = Image.query.order_by(db.func.random()).limit(5).all()

    # Get all model types for quick filters
    model_types = db.session.query(Model.type).distinct().all()
    model_types = [t[0] for t in model_types if t[0]]

    # Get all base models for filter dropdown
    base_models = db.session.query(ModelVersion.base_model).distinct().all()
    base_models = [m[0] for m in base_models if m[0]]

    return render_template(
        "index.html",
        random_models=random_models,
        featured_images=featured_images,
        model_types=model_types,
        base_models=base_models,
        current_nsfw=nsfw,
    )


@main.route("/models")
def models():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = current_app.config["MODELS_PER_PAGE"]

    # Base query
    query = Model.query

    # Filter options
    type_filter = request.args.get("type")
    base_model_filter = request.args.get("base_model")
    sort_by = request.args.get("sort", "newest")
    nsfw = request.args.get("nsfw", "false")
    tags = request.args.getlist("tags")

    # Apply filters
    if type_filter:
        query = query.filter(Model.type == type_filter)

    # Apply base model filter
    if base_model_filter:
        query = query.join(ModelVersion).filter(
            ModelVersion.base_model == base_model_filter
        )

    if nsfw == "false":
        query = query.filter(Model.nsfw == False)

    if tags:
        for tag in tags:
            query = query.join(Tag, Model.id == Tag.model_id).filter(Tag.tag == tag)

    # Apply sorting
    if sort_by == "newest":
        query = query.order_by(Model.id.desc())
    elif sort_by == "downloads":
        query = query.order_by(Model.download_count.desc())

    # Pagination
    pagination = query.paginate(page=page, per_page=per_page, error_out=False)
    models = pagination.items

    # Get all model types for filter dropdown
    model_types = db.session.query(Model.type).distinct().all()
    model_types = [t[0] for t in model_types if t[0]]

    # Get all base models for filter dropdown
    base_models = db.session.query(ModelVersion.base_model).distinct().all()
    base_models = [m[0] for m in base_models if m[0]]

    # Get popular tags
    popular_tags = (
        db.session.query(Tag.tag, db.func.count(Tag.id).label("count"))
        .group_by(Tag.tag)
        .order_by(db.text("count DESC"))
        .limit(20)
        .all()
    )

    return render_template(
        "models.html",
        models=models,
        pagination=pagination,
        model_types=model_types,
        base_models=base_models,
        popular_tags=popular_tags,
        current_filters={
            "type": type_filter,
            "base_model": base_model_filter,
            "sort": sort_by,
            "nsfw": nsfw,
            "tags": tags,
        },
    )


@main.route("/models/<int:model_id>")
def model_detail(model_id):
    model = Model.query.get_or_404(model_id)
    versions = (
        ModelVersion.query.filter_by(model_id=model_id)
        .order_by(ModelVersion.index_in_model.desc())
        .all()
    )

    # Get preview images
    preview_images = []
    for version in versions:
        images = Image.query.filter_by(model_version_id=version.id).limit(4).all()
        preview_images.extend(images)

    # Get model tags
    tags = Tag.query.filter_by(model_id=model_id).all()

    # Get similar models (models with same tags)
    tag_ids = [tag.tag for tag in tags]
    similar_models = (
        Model.query.join(Tag, Model.id == Tag.model_id)
        .filter(Model.id != model_id)
        .filter(Tag.tag.in_(tag_ids))
        .group_by(Model.id)
        .order_by(db.func.count(Tag.id).desc())
        .limit(6)
        .all()
    )

    # Get all model types for related models section
    model_types = db.session.query(Model.type).distinct().all()
    model_types = [t[0] for t in model_types if t[0]]

    # Get related models by type
    related_by_type = (
        Model.query.filter(Model.type == model.type)
        .filter(Model.id != model.id)
        .order_by(db.func.random())
        .limit(4)
        .all()
    )

    return render_template(
        "model_detail.html",
        model=model,
        versions=versions,
        preview_images=preview_images,
        tags=tags,
        similar_models=similar_models,
        related_by_type=related_by_type,
        model_types=model_types,
    )


@main.route("/creators")
def creators():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = current_app.config["CREATORS_PER_PAGE"]

    # Base query
    query = Creator.query

    # Sort options
    sort_by = request.args.get("sort", "models")

    # Apply sorting
    if sort_by == "models":
        query = (
            query.outerjoin(Model, Creator.id == Model.creator_id)
            .group_by(Creator.id)
            .order_by(db.func.count(Model.id).desc())
        )
    elif sort_by == "downloads":
        query = (
            query.outerjoin(Model, Creator.id == Model.creator_id)
            .group_by(Creator.id)
            .order_by(db.func.sum(Model.download_count).desc())
        )
    elif sort_by == "name":
        query = query.order_by(Creator.username)

    # Pagination
    pagination = query.paginate(page=page, per_page=per_page, error_out=False)
    creators = pagination.items

    # Get all model types for related navigation
    model_types = db.session.query(Model.type).distinct().all()
    model_types = [t[0] for t in model_types if t[0]]

    return render_template(
        "creators.html",
        creators=creators,
        pagination=pagination,
        current_sort=sort_by,
        model_types=model_types,
    )


@main.route("/creators/<int:creator_id>")
def creator_detail(creator_id):
    creator = Creator.query.get_or_404(creator_id)

    # Get creator's models
    models = (
        Model.query.filter_by(creator_id=creator_id).order_by(Model.id.desc()).all()
    )

    # Calculate statistics
    model_count = len(models)
    download_count = sum(model.download_count for model in models)

    # Get all model types
    model_types = db.session.query(Model.type).distinct().all()
    model_types = [t[0] for t in model_types if t[0]]

    return render_template(
        "creator_detail.html",
        creator=creator,
        models=models,
        model_count=model_count,
        download_count=download_count,
        model_types=model_types,
    )


@main.route("/search")
def search():
    query = request.args.get("q", "")
    base_model_filter = request.args.get("base_model", "")
    nsfw = request.args.get("nsfw", "false")
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = current_app.config["MODELS_PER_PAGE"]

    if not query:
        return redirect(url_for("main.index"))

    # Search models
    model_results = Model.query.filter(
        db.or_(Model.name.ilike(f"%{query}%"), Model.description.ilike(f"%{query}%"))
    )

    # Search creators
    creator_results = Creator.query.filter(Creator.username.ilike(f"%{query}%"))

    # Search tags
    tag_results = Tag.query.filter(Tag.tag.ilike(f"%{query}%"))

    # Get models from tag results
    tag_model_ids = [tag.model_id for tag in tag_results.all()]
    tag_models = Model.query.filter(Model.id.in_(tag_model_ids))

    # Combine model results
    combined_models = model_results.union(tag_models)

    # Apply base model filter if provided
    if base_model_filter:
        combined_models = combined_models.join(
            ModelVersion, Model.id == ModelVersion.model_id
        ).filter(ModelVersion.base_model == base_model_filter)

    # Apply NSFW filter
    if nsfw == "false":
        combined_models = combined_models.filter(Model.nsfw == False)

    # Pagination for models
    model_pagination = combined_models.paginate(
        page=page, per_page=per_page, error_out=False
    )
    models = model_pagination.items

    # Pagination for creators (simplified)
    creators = creator_results.limit(5).all()

    # Get all base models for filter dropdown

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CIVITR{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <i class="fas fa-cube me-2"></i> CIVITR
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-th-large me-1"></i> Models
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('main.models') }}">All Models</a></li>
                            <li><hr class="dropdown-divider"></li>
                            {% for type in model_types %}
                            <li><a class="dropdown-item" href="{{ url_for('main.models', type=type) }}">{{ type }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.creators') }}">
                            <i class="fas fa-users me-1"></i> Creators
                        </a>
                    </li>
                    
                </ul>
                <form class="d-flex" action="{{ url_for('main.search') }}" method="get">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search models, creators, tags..." aria-label="Search">
                    <button class="btn btn-outline-light" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-dark text-light mt-5 py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>CIVITR</h5>
                    <!-- <div class="social-icons mt-3">
                        <a href="#" class="me-2"><i class="fab fa-twitter fa-lg"></i></a>
                        <a href="#" class="me-2"><i class="fab fa-discord fa-lg"></i></a>
                        <a href="#" class="me-2"><i class="fab fa-github fa-lg"></i></a>
                    </div> -->
                </div>
                <div class="col-md-4">
                    <!--<h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="{{ url_for('main.index') }}">Home</a></li>
                        <li><a href="{{ url_for('main.models') }}">Browse Models</a></li>
                        <li><a href="{{ url_for('main.creators') }}">Creators</a></li>
                    </ul> -->
                </div>
                <div class="col-md-4 text-md-end">
                    <!--<h5>Categories</h5>
                    <div class="d-flex flex-wrap justify-content-md-end">
                        {% for type in model_types %}
                        <a href="{{ url_for('main.models', type=type) }}" class="badge bg-primary me-1 mb-1">{{ type }}</a>
                        {% endfor %}
                    </div>--->
                    
                </div>
            </div>
        </div>
    </footer>

    <!-- Back to top button -->
    <button id="back-to-top" class="btn btn-primary btn-sm rounded-circle">
        <i class="fas fa-arrow-up"></i>
    </button>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/creators.html
{% extends "base.html" %}

{% block title %}Creators - CIVITR{% endblock %}

{% block content %}
<h1 class="mb-4">Model Creators</h1>

<div class="row mb-4">
    <div class="col-md-6">
        <form action="{{ url_for('main.creators') }}" method="get" class="d-flex">
            <select class="form-select me-2" name="sort" onchange="this.form.submit()">
                <option value="models" {% if current_sort == 'models' %}selected{% endif %}>Sort by Most Models</option>
                <option value="downloads" {% if current_sort == 'downloads' %}selected{% endif %}>Sort by Most Downloads</option>
                <option value="name" {% if current_sort == 'name' %}selected{% endif %}>Sort by Name</option>
            </select>
            <button type="submit" class="btn btn-primary">Apply</button>
        </form>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for creator in creators %}
    <div class="col">
        <div class="card h-100">
            <div class="card-body text-center">
                <img src="{{ creator.image or url_for('static', filename='img/default-avatar.png') }}" 
                     alt="{{ creator.username }}" class="rounded-circle mb-3" style="width: 100px; height: 100px;">
                <h5 class="card-title">{{ creator.username }}</h5>
                
                <div class="creator-stats d-flex justify-content-around my-3">
                    <div class="text-center">
                        <div class="h5 mb-0">{{ creator.models.count() }}</div>
                        <small class="text-muted">Models</small>
                    </div>
                    <div class="text-center">
                        <div class="h5 mb-0">
                            {{ creator.models.count() > 0 and creator.models.all()|sum(attribute='download_count') or 0 }}
                        </div>
                        <small class="text-muted">Downloads</small>
                    </div>
                </div>
                
                <a href="{{ url_for('main.creator_detail', creator_id=creator.id) }}" class="btn btn-outline-primary">View Profile</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Pagination -->
<div class="pagination-container mt-4">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if pagination.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('main.creators', page=pagination.prev_num, sort=current_sort) }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
            {% endif %}
            
            {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if page_num %}
            <li class="page-item {% if page_num == pagination.page %}active{% endif %}">
                <a class="page-link" href="{{ url_for('main.creators', page=page_num, sort=current_sort) }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            {% endif %}
            {% endfor %}
            
            {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('main.creators', page=pagination.next_num, sort=current_sort) }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}CIVITR - Home{% endblock %}

{% block content %}
<!-- Quick Filter Controls -->
<div class="quick-filters mb-4">
    <div class="card">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h5 class="mb-3">Quick Filters</h5>
                    <div class="d-flex flex-wrap gap-2">
                        {% for type in model_types %}
                        <a href="{{ url_for('main.models', type=type) }}" class="btn btn-filter">{{ type }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{ url_for('main.index') }}" method="get">
                                <div class="form-check form-switch mb-0">
                                    <input class="form-check-input" type="checkbox" name="nsfw" value="true" id="nsfwCheck" {% if current_nsfw == 'true' %}checked{% endif %} onchange="this.form.submit()">
                                    <label class="form-check-label" for="nsfwCheck">
                                        Include NSFW Content
                                    </label>
                                    {% if current_nsfw != 'true' %}
                                    <input type="hidden" name="nsfw" value="false">
                                    {% endif %}
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <form action="{{ url_for('main.models') }}" method="get" class="d-flex align-items-center">
                                <select class="form-select form-select-sm" name="base_model" onchange="this.form.submit()">
                                    <option value="">Filter by Base Model</option>
                                    {% for base_model in base_models %}
                                    <option value="{{ base_model }}">{{ base_model }}</option>
                                    {% endfor %}
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Enhanced Hero Banner -->
<div class="hero-banner mb-5">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            {% for image in featured_images %}
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}" 
                    {% if loop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ loop.index }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for image in featured_images %}
            <div class="carousel-item {% if loop.first %}active{% endif %}">
                <img src="{{ image.url }}" class="d-block w-100" alt="Featured Image">
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<!-- Featured Categories Section 
<div class="featured-categories mb-5">
    <div class="row mb-4">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <h2 class="section-title">Popular Categories</h2>
            </div>
            <hr>
        </div>
    </div>
    <div class="row g-4">
        {% for type in model_types[:4] %}
        <div class="col-md-3">
            <a href="{{ url_for('main.models', type=type) }}" class="category-card">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="category-icon mb-3">
                            <i class="fas fa-cube fa-3x"></i>
                        </div>
                        <h5 class="card-title">{{ type }}</h5>
                        <p class="card-text text-muted">Explore {{ type }} models</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div> -->

<!-- Random Models Section -->
<div class="row mb-4">
    <div class="col-12">
        <div class="d-flex justify-content-between align-items-center">
            <h2 class="section-title">Discover Random Models</h2>
            <a href="{{ url_for('main.models') }}" class="btn btn-outline-primary">View All Models</a>
        </div>
        <hr>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-5 g-4 mb-5">
    {% for model in random_models %}
    <div class="col">
        <div class="card h-100 model-card">
            {% set preview_image = model.versions.first().images.first() if model.versions.count() > 0 and model.versions.first().images.count() > 0 else none %}
            <div class="card-img-wrapper">
                {% if preview_image %}
                <img src="{{ preview_image.url }}" class="card-img-top" alt="{{ model.name }}">
                {% else %}
                <div class="card-img-placeholder">
                    <i class="fas fa-image fa-3x"></i>
                </div>
                {% endif %}
                {% if model.nsfw %}
                <span class="nsfw-badge">NSFW</span>
                {% endif %}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ model.name }}</h5>
                <div class="model-info mb-2">
                    <span class="badge bg-secondary me-1">{{ model.type }}</span>
                    {% if model.first_version and model.first_version.base_model %}
                    <span class="badge bg-info">{{ model.first_version.base_model }}</span>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">
                        {% if model.creator_id and model.creator %}
                            By <a href="{{ url_for('main.creator_detail', creator_id=model.creator_id) }}">{{ model.creator.username }}</a>
                        {% else %}
                            By Unknown
                        {% endif %}
                    </small>
                    <span class="badge bg-primary"><i class="fas fa-download"></i> {{ model.download_count }}</span>
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ url_for('main.model_detail', model_id=model.id) }}" class="btn btn-sm btn-outline-primary w-100">View Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Refresh Button -->
<div class="text-center mb-5">
    <a href="{{ url_for('main.index', nsfw=current_nsfw) }}" class="btn btn-primary">
        <i class="fas fa-random me-2"></i> Show Me More Random Models
    </a>
</div>
{% endblock %}